export const itemsByGrade = {
  1: [
    {
      name: 'F Major scale',
      root: 'F2',
      type: 'major',
      categories: ['scale'],
      octaves: 1,
      notes: ['F2', 'G2', 'A2', 'Bb2', 'C3', 'D3', 'E3', 'F3', 'F3', 'E3', 'D3', 'C3', 'Bb2', 'A2', 'G2', 'F2'],
    },
    {
      name: 'Chromatic commencing on F',
      root: 'F2',
      type: 'chromatic',
      categories: ['scale'],
      octaves: 1,
      notes: ['F2', 'F#2', 'G2', 'G#2', 'A2', 'Bb2', 'B2', 'C3', 'C#3', 'D3', 'D#3', 'E3', 'F3', 'F3', 'E3', 'Eb3', 'D3', 'Db3', 'C3', 'B2', 'Bb2', 'A2', 'Ab2', 'G2', 'Gb2', 'F2'],
    },
    {
      name: 'F Major arpeggio / broken chord',
      root: 'F2',
      type: 'major',
      categories: ['arpeggio', 'broken'],
      octaves: 1,
      notes: ['F2', 'A2', 'C3', 'F3', 'C3', 'A2', 'F2'],
    },
  ],
  2: [
    {
      name: 'C Major scale',
      root: 'C3',
      type: 'major',
      categories: ['scale'],
      octaves: 1,
      notes: ['C3', 'D3', 'E3', 'F3', 'G3', 'A3', 'B3', 'C4', 'B3', 'A3', 'G3', 'F3', 'E3', 'D3', 'C3'],
    },
    {
      name: 'F Major scale',
      root: 'F2',
      type: 'major',
      categories: ['scale'],
      octaves: 1.5,
      notes: ['F2', 'G2', 'A2', 'Bb2', 'C3', 'D3', 'E3', 'F3', 'G3', 'A3', 'Bb3', 'A3', 'G3', 'F3', 'E3', 'D3', 'C3', 'Bb2', 'A2', 'G2', 'F2'],
    },
    {
      name: 'A harmonic minor scale',
      root: 'A2',
      type: 'harmonic minor',
      categories: ['scale'],
      octaves: 1,
      notes: ['A2', 'B2', 'C3', 'D3', 'E3', 'F3', 'G#3', 'A3', 'G#3', 'F3', 'E3', 'D3', 'C3', 'B2', 'A2'],
    },
    {
      name: 'A melodic minor scale',
      root: 'A2',
      type: 'melodic minor',
      categories: ['scale'],
      octaves: 1,
      notes: ['A2', 'B2', 'C3', 'D3', 'E3', 'F#3', 'G#3', 'A3', 'G3', 'F3', 'E3', 'D3', 'C3', 'B2', 'A2'],
    },
    {
      name: 'Chromatic commencing on F',
      root: 'F2',
      type: 'chromatic',
      categories: ['scale'],
      octaves: 1.5,
      notes: ['F2', 'F#2', 'G2', 'G#2', 'A2', 'Bb2', 'B2', 'C3', 'C#3', 'D3', 'D#3', 'E3', 'F3', 'F#3', 'G3', 'G#3', 'A3', 'A3', 'Ab3', 'G3', 'Gb3', 'F3', 'E3', 'Eb3', 'D3', 'Db3', 'C3', 'B2', 'Bb2', 'A2', 'Ab2', 'G2', 'Gb2', 'F2'],
    },
    {
      name: 'C Major arpeggio',
      root: 'C3',
      type: 'major',
      categories: ['arpeggio'],
      octaves: 1,
      notes: ['C3', 'E3', 'G3', 'C4', 'G3', 'E3', 'C3'],
    },
    {
      name: 'A minor arpeggio',
      root: 'A2',
      type: 'minor',
      categories: ['arpeggio'],
      octaves: 1,
      notes: ['A2', 'C3', 'E3', 'A3', 'E3', 'C3', 'A2'],
    },
    {
      name: 'F Major arpeggio',
      root: 'F2',
      type: 'major',
      categories: ['arpeggio'],
      octaves: 1.5,
      notes: ['F2', 'A2', 'C3', 'F3', 'A3', 'F3', 'C3', 'A2', 'F2'],
    },
    {
      name: 'C Major broken chord',
      root: 'C3',
      type: 'major',
      categories: ['broken'],
      octaves: 1,
      notes: ['C3', 'E3', 'G3', 'E3', 'G3', 'C4', 'C4', 'G3', 'E3', 'G3', 'E3', 'C3', 'C3'],
    },
    {
      name: 'A minor broken chord',
      root: 'A2',
      type: 'minor',
      categories: ['broken'],
      octaves: 1,
      notes: ['A2', 'C3', 'E3', 'C3', 'E3', 'A3', 'A3', 'E3', 'C3', 'E3', 'C3', 'A2', 'A2'],
    },
    {
      name: 'F Major broken chord',
      root: 'F2',
      type: 'major',
      categories: ['broken'],
      octaves: 1.5,
      notes: ['F2', 'A2', 'C3', 'A2', 'C3', 'F3', 'A3', 'A3', 'F3', 'C3', 'A2', 'C3', 'A2', 'F2', 'F2'],
    },
  ],
};
