export const itemsByGrade = {
  1: [
    {
      name: 'F Major scale',
      root: 'F2',
      type: 'major',
      categories: ['scale'],
      octaves: 1,
      notes: ['F2', 'G2', 'A2', 'Bb2', 'C3', 'D3', 'E3', 'F3', 'F3', 'E3', 'D3', 'C3', 'Bb2', 'A2', 'G2', 'F2'],
    },
    {
      name: 'Chromatic commencing on F',
      root: 'F2',
      type: 'chromatic',
      categories: ['scale'],
      octaves: 1,
      notes: ['F2', 'F#2', 'G2', 'G#2', 'A2', 'Bb2', 'B2', 'C3', 'C#3', 'D3', 'D#3', 'E3', 'F3', 'F3', 'E3', 'Eb3', 'D3', 'Db3', 'C3', 'B2', 'Bb2', 'A2', 'Ab2', 'G2', 'Gb2', 'F2'],
    },
    {
      name: 'F Major arpeggio / broken chord',
      root: 'F2',
      type: 'major',
      categories: ['arpeggio', 'broken'],
      octaves: 1,
      notes: ['F2', 'A2', 'C3', 'F3', 'C3', 'A2', 'F2'],
    },
  ],
  2: [
    {
      name: 'C Major scale',
      root: 'C3',
      type: 'major',
      categories: ['scale'],
      octaves: 1,
      notes: ['C3', 'D3', 'E3', 'F3', 'G3', 'A3', 'B3', 'C4', 'B3', 'A3', 'G3', 'F3', 'E3', 'D3', 'C3'],
    },
    {
      name: 'F Major scale',
      root: 'F2',
      type: 'major',
      categories: ['scale'],
      octaves: 1.5,
      notes: ['F2', 'G2', 'A2', 'Bb2', 'C3', 'D3', 'E3', 'F3', 'G3', 'A3', 'Bb3', 'A3', 'G3', 'F3', 'E3', 'D3', 'C3', 'Bb2', 'A2', 'G2', 'F2'],
    },
    {
      name: 'A harmonic minor scale',
      root: 'A2',
      type: 'harmonic minor',
      categories: ['scale'],
      octaves: 1,
      notes: ['A2', 'B2', 'C3', 'D3', 'E3', 'F3', 'G#3', 'A3', 'G#3', 'F3', 'E3', 'D3', 'C3', 'B2', 'A2'],
    },
    {
      name: 'A melodic minor scale',
      root: 'A2',
      type: 'melodic minor',
      categories: ['scale'],
      octaves: 1,
      notes: ['A2', 'B2', 'C3', 'D3', 'E3', 'F#3', 'G#3', 'A3', 'G3', 'F3', 'E3', 'D3', 'C3', 'B2', 'A2'],
    },
    {
      name: 'Chromatic commencing on F',
      root: 'F2',
      type: 'chromatic',
      categories: ['scale'],
      octaves: 1.5,
      notes: ['F2', 'F#2', 'G2', 'G#2', 'A2', 'Bb2', 'B2', 'C3', 'C#3', 'D3', 'D#3', 'E3', 'F3', 'F#3', 'G3', 'G#3', 'A3', 'A3', 'Ab3', 'G3', 'Gb3', 'F3', 'E3', 'Eb3', 'D3', 'Db3', 'C3', 'B2', 'Bb2', 'A2', 'Ab2', 'G2', 'Gb2', 'F2'],
    },
    {
      name: 'C Major arpeggio',
      root: 'C3',
      type: 'major',
      categories: ['arpeggio'],
      octaves: 1,
      notes: ['C3', 'E3', 'G3', 'C4', 'G3', 'E3', 'C3'],
    },
    {
      name: 'A minor arpeggio',
      root: 'A2',
      type: 'minor',
      categories: ['arpeggio'],
      octaves: 1,
      notes: ['A2', 'C3', 'E3', 'A3', 'E3', 'C3', 'A2'],
    },
    {
      name: 'F Major arpeggio',
      root: 'F2',
      type: 'major',
      categories: ['arpeggio'],
      octaves: 1.5,
      notes: ['F2', 'A2', 'C3', 'F3', 'A3', 'F3', 'C3', 'A2', 'F2'],
    },
    {
      name: 'C Major broken chord',
      root: 'C3',
      type: 'major',
      categories: ['broken'],
      octaves: 1,
      notes: ['C3', 'E3', 'G3', 'E3', 'G3', 'C4', 'C4', 'G3', 'E3', 'G3', 'E3', 'C3', 'C3'],
    },
    {
      name: 'A minor broken chord',
      root: 'A2',
      type: 'minor',
      categories: ['broken'],
      octaves: 1,
      notes: ['A2', 'C3', 'E3', 'C3', 'E3', 'A3', 'A3', 'E3', 'C3', 'E3', 'C3', 'A2', 'A2'],
    },
    {
      name: 'F Major broken chord',
      root: 'F2',
      type: 'major',
      categories: ['broken'],
      octaves: 1.5,
      notes: ['F2', 'A2', 'C3', 'A2', 'C3', 'F3', 'A3', 'A3', 'F3', 'C3', 'A2', 'C3', 'A2', 'F2', 'F2'],
    },
  ],
  3: [
    {
      name: 'G Major scale',
      root: 'G2',
      type: 'major',
      categories: ['scale'],
      octaves: 1.5,
      notes: ['G2', 'A2', 'B2', 'C3', 'D3', 'E3', 'F#3', 'G3', 'A3', 'B3', 'C4', 'D4', 'C4', 'B3', 'A3', 'G3', 'F#3', 'E3', 'D3', 'C3', 'B2', 'A2', 'G2'],
    },
    {
      name: 'G harmonic minor scale',
      root: 'G2',
      type: 'harmonic minor',
      categories: ['scale'],
      octaves: 1.5,
      notes: ['G2', 'A2', 'Bb2', 'C3', 'D3', 'Eb3', 'F#3', 'G3', 'A3', 'Bb3', 'C4', 'D4', 'C4', 'Bb3', 'A3', 'G3', 'F#3', 'Eb3', 'D3', 'C3', 'Bb2', 'A2', 'G2'],
    },
    {
      name: 'G melodic minor scale',
      root: 'G2',
      type: 'melodic minor',
      categories: ['scale'],
      octaves: 1.5,
      notes: ['G2', 'A2', 'Bb2', 'C3', 'D3', 'E3', 'F#3', 'G3', 'A3', 'B3', 'C4', 'D4', 'C4', 'Bb3', 'A3', 'G3', 'F3', 'Eb3', 'D3', 'C3', 'Bb2', 'A2', 'G2'],
    },
    {
      name: 'Bb Major scale',
      root: 'Bb2',
      type: 'major',
      categories: ['scale'],
      octaves: 1.5,
      notes: ['Bb2', 'C3', 'D3', 'Eb3', 'F3', 'G3', 'A3', 'Bb3', 'C4', 'D4', 'Eb4', 'F4', 'Eb4', 'D4', 'C4', 'Bb3', 'A3', 'G3', 'F3', 'Eb3', 'D3', 'C3', 'Bb2'],
    },
    {
      name: 'C Major scale',
      root: 'C3',
      type: 'major',
      categories: ['scale'],
      octaves: 2,
      notes: ['C3', 'D3', 'E3', 'F3', 'G3', 'A3', 'B3', 'C4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C5', 'B4', 'A4', 'G4', 'F4', 'E4', 'D4', 'C4', 'B3', 'A3', 'G3', 'F3', 'E3', 'D3', 'C3'],
    },
    {
      name: 'D harmonic minor scale',
      root: 'D3',
      type: 'harmonic minor',
      categories: ['scale'],
      octaves: 2,
      notes: ['D3', 'E3', 'F3', 'G3', 'A3', 'Bb3', 'C#4', 'D4', 'E4', 'F4', 'G4', 'A4', 'Bb4', 'C#5', 'D5', 'C#5', 'Bb4', 'A4', 'G4', 'F4', 'E4', 'D4', 'C#4', 'Bb3', 'A3', 'G3', 'F3', 'E3', 'D3'],
    },
    {
      name: 'D melodic minor scale',
      root: 'D3',
      type: 'melodic minor',
      categories: ['scale'],
      octaves: 2,
      notes: ['D3', 'E3', 'F3', 'G3', 'A3', 'B3', 'C#4', 'D4', 'E4', 'F4', 'G4', 'A4', 'B4', 'C#5', 'D5', 'C5', 'Bb4', 'A4', 'G4', 'F4', 'E4', 'D4', 'C4', 'Bb3', 'A3', 'G3', 'F3', 'E3', 'D3'],
    },
    {
      name: 'F Major scale',
      root: 'F2',
      type: 'major',
      categories: ['scale'],
      octaves: 2,
      notes: ['F2', 'G2', 'A2', 'Bb2', 'C3', 'D3', 'E3', 'F3', 'G3', 'A3', 'Bb3', 'C4', 'D4', 'E4', 'F4', 'E4', 'D4', 'C4', 'Bb3', 'A3', 'G3', 'F3', 'E3', 'D3', 'C3', 'Bb2', 'A2', 'G2', 'F2'],
    },
    {
      name: 'C Major scale in thirds',
      root: 'C3',
      type: 'major',
      categories: ['scale'],
      octaves: 2,
      notes: ['C3', 'E3', 'D3', 'F3', 'E3', 'G3', 'F3', 'A3', 'G3', 'B3', 'A3', 'C4', 'B3', 'D4', 'C4', 'E4', 'D4', 'F4', 'E4', 'G4', 'F4', 'A4', 'G4', 'B4', 'A4', 'C5', 'G4', 'E4', 'F4', 'D4', 'E4', 'C4', 'D4', 'B3', 'C4', 'A3', 'B3', 'G3', 'A3', 'F3', 'G3', 'E3', 'F3', 'D3', 'E3', 'C3'],
    },
    {
      name: 'F Major scale in thirds',
      root: 'F2',
      type: 'major',
      categories: ['scale'],
      octaves: 2,
      notes: ['F2', 'A2', 'G2', 'Bb2', 'A2', 'C3', 'Bb2', 'D3', 'C3', 'E3', 'D3', 'F3', 'E3', 'G3', 'F3', 'A3', 'G3', 'Bb3', 'A3', 'C4', 'Bb3', 'D4', 'C4', 'E4', 'D4', 'F4', 'C4', 'A3', 'Bb3', 'G3', 'A3', 'F3', 'G3', 'E3', 'F3', 'D3', 'E3', 'C3', 'D3', 'Bb2', 'C3', 'A2', 'Bb2', 'G2', 'A2', 'F2'],
    },
    {
      name: 'Chromatic commencing on C',
      root: 'C3',
      type: 'chromatic',
      categories: ['scale'],
      octaves: 2,
      notes: ['C3', 'C#3', 'D3', 'D#3', 'E3', 'F3', 'F#3', 'G3', 'G#3', 'A3', 'A#3', 'B3', 'C4', 'C#4', 'D4', 'D#4', 'E4', 'F4', 'F#4', 'G4', 'G#4', 'A4', 'B4', 'Bb4', 'A4', 'Ab4', 'G4', 'Gb4', 'F4', 'E4', 'Eb4', 'D4', 'Db4', 'C4', 'B3', 'Bb3', 'A3', 'Ab3', 'G3', 'Gb3', 'F3', 'E3', 'Eb3', 'D3', 'Db3', 'C3'],
    },
    {
      name: 'Chromatic commencing on F',
      root: 'F2',
      type: 'chromatic',
      categories: ['scale'],
      octaves: 2,
      notes: ['F2', 'F#2', 'G2', 'G#2', 'A2', 'A#2', 'B2', 'C3', 'C#3', 'D3', 'D#3', 'E3', 'F3', 'F#3', 'G3', 'G#3', 'A3', 'A#3', 'B3', 'C4', 'C#4', 'D4', 'D#4', 'E4', 'F4', 'E4', 'Eb4', 'D4', 'Db4', 'C4', 'B3', 'Bb3', 'A3', 'Ab3', 'G3', 'Gb3', 'F3', 'E3', 'Eb3', 'D3', 'Db3', 'C3', 'B2', 'Bb2', 'A2', 'Ab2', 'G2', 'Gb2', 'F2'],
    },
    {
      name: 'G Major arpeggio',
      root: 'D2',
      type: 'major',
      categories: ['arpeggio'],
      octaves: 1.5,
      notes: ['D2', 'G2', 'B2', 'D3', 'G3', 'D3', 'B2', 'G2', 'D2'],
    },
    {
      name: 'G minor arpeggio',
      root: 'D2',
      type: 'minor',
      categories: ['arpeggio'],
      octaves: 1.5,
      notes: ['D2', 'G2', 'Bb2', 'D3', 'G3', 'D3', 'Bb2', 'G2', 'D2'],
    },
    {
      name: 'Bb Major arpeggio',
      root: 'F2',
      type: 'major',
      categories: ['arpeggio'],
      octaves: 1.5,
      notes: ['F2', 'Bb2', 'D3', 'F3', 'Bb3', 'F3', 'D3', 'Bb2', 'F2'],
    },
    {
      name: 'C Major arpeggio',
      root: 'C3',
      type: 'major',
      categories: ['arpeggio'],
      octaves: 2,
      notes: ['C3', 'E3', 'G3', 'C4', 'E4', 'G4', 'C5', 'G4', 'E4', 'C4', 'G3', 'E3', 'C3'],
    },
    {
      name: 'D minor arpeggio',
      root: 'D3',
      type: 'minor',
      categories: ['arpeggio'],
      octaves: 2,
      notes: ['D3', 'F3', 'A3', 'D4', 'F4', 'A4', 'D5', 'A4', 'F4', 'D4', 'A3', 'F3', 'D3'],
    },
    {
      name: 'F Major arpeggio',
      root: 'F2',
      type: 'major',
      categories: ['arpeggio'],
      octaves: 2,
      notes: ['F2', 'A2', 'C3', 'F3', 'A3', 'C4', 'F4', 'C4', 'A3', 'F3', 'C3', 'A2', 'F2'],
    },
    {
      name: 'G Major broken chord',
      root: 'G2',
      type: 'major',
      categories: ['broken'],
      octaves: 1.5,
      notes: ['G2', 'B2', 'D3', 'B2', 'D3', 'G3', 'B3', 'B3', 'G3', 'D3', 'B2', 'D3', 'B2', 'G2', 'G2'],
    },
    {
      name: 'G minor broken chord',
      root: 'G2',
      type: 'minor',
      categories: ['broken'],
      octaves: 1.5,
      notes: ['G2', 'Bb2', 'D3', 'Bb2', 'D3', 'G3', 'Bb3', 'Bb3', 'G3', 'D3', 'Bb2', 'D3', 'Bb2', 'G2', 'G2'],
    },
    {
      name: 'Bb Major broken chord',
      root: 'Bb2',
      type: 'major',
      categories: ['broken'],
      octaves: 1.5,
      notes: ['Bb2', 'D3', 'F3', 'D3', 'F3', 'Bb3', 'D4', 'D4', 'Bb3', 'F3', 'D3', 'F3', 'D3', 'Bb2', 'Bb2'],
    },
    {
      name: 'C Major broken chord',
      root: 'C3',
      type: 'major',
      categories: ['broken'],
      octaves: 2,
      notes: ['C3', 'E3', 'G3', 'E3', 'G3', 'C4', 'E4', 'E4', 'C4', 'G3', 'E3', 'G3', 'E3', 'C3', 'C3'],
    },
    {
      name: 'D minor broken chord',
      root: 'D3',
      type: 'minor',
      categories: ['broken'],
      octaves: 2,
      notes: ['D3', 'F3', 'A3', 'F3', 'A3', 'D4', 'F4', 'F4', 'D4', 'A3', 'F3', 'A3', 'F3', 'D3', 'D3'],
    },
    {
      name: 'F Major broken chord',
      root: 'F2',
      type: 'major',
      categories: ['broken'],
      octaves: 2,
      notes: ['F2', 'A2', 'C3', 'A2', 'C3', 'F3', 'A3', 'A3', 'F3', 'C3', 'A2', 'C3', 'A2', 'F2', 'F2'],
    },
  ],
};
